[package]
name = "tut"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
mongodb = "3.2.1"
rust-tradier = { path = "../rust-tradier" }
serde = "1.0.218"
serde_json = "1.0.139"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
uuid7 = "1.1.0"
